meta_product_name: "Event Mates"
meta_title: 'Event Mates - Your gateway to shared experiences'
meta_description: 'Our platform connects fans so they can attend events together, forge new friendships, and create memories that last forever.'
meta_image: "meta_image.jpg" # should exist in `app/assets/images/`